### ISSUE TITLE
Component capturing click events

### ISSUE THREAD

**Issue by heatherbooker** [tiagovtristao/react-table-container#3]
Hi,

I seem to have noticed that the presence of this component on a page leads to not being able to use the cursor to click and drag for text selection/highlighting.

I tried to debug by removing the `event.preventDefault` calls but wasn't able to resolve it. Any clues why it might be happening or a fix would be highly appreciated!

Thanks! :)

**Comment by heatherbooker** [comment]
Update! I think I had caching issues, it seems that removing all the event.preventDefaults does in fact resolve the issue!

Obviously they were there for a reason and without them the page scrolls as well as the table scrolling which is not ideal >< So will take more finagling to fix cleanly.

**Comment by tiagovtristao** [comment]
Well spotted @heatherbooker!

Yes, I'm preventing the default behaviour in most events (if not all of them) so I can take over the browser's implementation which in this project is sometimes undesirable.

The text selection was indeed something I forgot to test. I'm taking a look at your pull request. Thanks!
