### ISSUE TITLE
Doesn't work with react components instead of plain table

### ISSUE THREAD

**Issue by hoschi** [tiagovtristao/react-table-container#6]
E.g.: https://material-ui.com/demos/tables/

Because you [query for HTML elements only](https://github.com/tiagovtristao/react-table-container/blob/master/src/ReactTableContainer.tsx#L75). Can you make the elements it searches for configurable?

**Comment by tiagovtristao** [comment]
Hi @hoschi. Thanks for your message.

You are right, it only queries HTML table elements at the moment. That was the idea from the beginning to give the html table tag a visually fixed header.

Looking at https://material-ui.com/demos/tables/ I can see that the components render valid html tables in end, so it makes sense to also add support for those types of components.

I'll start looking into it this weekend :-)

**Comment by tiagovtristao** [comment]
Hi @hoschi, 

I apologise for the long time taken, but your request is now available in the new version. Just run `npm install --save react-table-container@1.0.0`

Thanks!

**Comment by hoschi** [comment]
@tiagovtristao Nice! I'm working on another big feature at the moment, but I'll try this definitely. Thanks for looking into this!
