### ISSUE TITLE
React table container with react popout Issue

### ISSUE THREAD

**Issue by GoChartingAdmin** [tiagovtristao/react-table-container#7]
Hi there

I am using your nice lib in our production.  The table works just fine until I use a popout window using the react-popout library.

[https://github.com/JakeGinnivan/react-popout]React-popout

In the popped out window, there are two issues that I am facing:
1. The table header looks like below before popout (which is perfect)
![image](https://user-images.githubusercontent.com/20324844/45476323-fb7e1680-b73e-11e8-9d27-e88b6bab9bf2.png)

But after popout the table header looks like below

![image](https://user-images.githubusercontent.com/20324844/45476673-d6d66e80-b73f-11e8-800a-abbf206af209.png)

2. the scroller becomes non-draggable with the mouse.  It works when I use the mousewheel though.  

My code:

```
function copyStyles(sourceDoc, targetDoc) {
  Array.from(sourceDoc.styleSheets).forEach(styleSheet => {
    if (styleSheet.cssRules) { // for <style> elements
      const newStyleEl = sourceDoc.createElement('style');

      Array.from(styleSheet.cssRules).forEach(cssRule => {
        // write the text of each rule into the body of the style element
        newStyleEl.appendChild(sourceDoc.createTextNode(cssRule.cssText));
      });

      targetDoc.head.appendChild(newStyleEl);
    } else if (styleSheet.href) { // for <link> elements loading CSS from a URL
      const newLinkEl = sourceDoc.createElement('link');

      newLinkEl.rel = 'stylesheet';
      newLinkEl.href = styleSheet.href;
      targetDoc.head.appendChild(newLinkEl);
    }
  });
}
const App = props => {
    return (
        <Popout>
            {
                popoutWindow => {
                    copyStyles(window.document, popoutWindow.document);
                    return (
                        <div>
                            ...
                        </div>
                    );
                }
            }
        </Popout>
    )
}
```

Any suggestions

**Comment by tiagovtristao** [comment]
Hi @GoChartingAdmin,

I apologise for the late reply.

I tried to run the code snippet above, but react-popout is throwing errors. Would you mind trying to replicate the issues you are facing in, for instance, codesandbox, so I can inspect it better?

Many thanks.

**Comment by tiagovtristao** [comment]
I'll be closing this issue for now due to its inactivity. Feel free to re-open it, if the problem persists.
