### ISSUE TITLE
Overwrite using the `style` props

### ISSUE THREAD

**Issue by nyxynyx** [tiagovtristao/react-table-container#8]
I am unable to overwrite the default styles for `ReactTableContainer` component by passing in the style props.

    <ReactTableContainer width="auto" height="300px" style={{display: 'display: block'}}>

After the component is rendered, we still see `display: inline-block`. Any ideas?

**Comment by tiagovtristao** [comment]
Hi @nyxynyx,

There are a few properties that `ReactTableContainer` won't allow to be overridden to guarantee its base functionality - `display: inline-block` is one of few ones.

In your example above, having `width="auto"` and `style={{display: 'display: block'}}` (assuming it could be overridden) would yield the same thing as just `width="100%"`, if there is no other CSS affecting the layout.

I can consider removing the constraint of not allowing certain properties to be overridden, if you are trying to achieve something that `ReactTableContainer` can't already do without changing these hard coded properties.

Would you mind setting up an example of what you are trying to achieve somewhere (i.e., codesandbox)?

Thanks!

**Comment by tiagovtristao** [comment]
I'll be closing this issue for now due to its inactivity. Feel free to re-open it, if the problem persists.
