### ISSUE TITLE
Dynamic row add thead not adjust accordingly

### ISSUE THREAD

**Issue by thakuranujsingh** [tiagovtristao/react-table-container#9]
1. If we add dynamic <tr> the <thead> is not adjusted accordingly, Please check the attached screenshot
2. Could we fix footer as well?

![Screenshot 2019-04-26 at 1 28 06 PM](https://user-images.githubusercontent.com/17110050/56792460-43adfd00-6827-11e9-9990-7fc06acbbf62.png)

**Comment by tiagovtristao** [comment]
Hi @thakuranujsingh,

1) How are you dynamically adding new content to the table? Can you please provide a working example using, for instance, CodeSandbox?
2) What do you mean by the fixing the footer? Locking it at the bottom of the table in a similar way to how the header works in this package?

Thanks!

**Comment by tiagovtristao** [comment]
I'll be closing this issue for now due to its inactivity. Feel free to re-open it, if the problem persists.

**Comment by dfebb** [comment]
Hello @tiagovtristao, I've found a similar problem and I think I see what @thakuranujsingh was trying to explain.

Please take a look at https://codesandbox.io/embed/react-table-container-y9l4c , this seems to happen when you have (at least?) 2 rows as part of your table header.
